"use client";

import React, { useState, useEffect } from "react";
import { DashboardShell } from "@/components/templates/DashboardShell";
import { DashboardSidebar } from "@/components/organisms/DashboardSidebar";
import { SignedIn, SignedOut, useAuth } from "@/auth/clerk";
import { SignedOutPanel } from "@/components/auth/SignedOutPanel";
import { FileText, Linkedin, Twitter, Check, X, Edit3, Clock, AlertCircle } from "lucide-react";

type Draft = {
    id: string;
    content: string;
    platform: string;
    status: string;
    agent: string;
    created_at: string;
};

export default function DraftsPage() {
    const { getToken, isSignedIn } = useAuth();
    const [drafts, setDrafts] = useState<Draft[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    const fetchDrafts = async () => {
        try {
            const token = await getToken();
            const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/drafts`, {
                headers: { 'Authorization': `Bearer ${token}` }
            });
            const data = await res.json();
            if (data.success) {
                const raw = data.drafts || data.items || [];
                setDrafts(raw.map((d: any) => ({
                    ...d,
                    id: d._id || d.id,
                    created_at: d._creationTime ? new Date(d._creationTime).toISOString() : new Date().toISOString()
                })));
            }
        } catch (err) {
            console.error("Failed to fetch drafts", err);
        } finally {
            setIsLoading(false);
        }
    };

    useEffect(() => {
        if (isSignedIn) {
            fetchDrafts();
        }
    }, [isSignedIn]);

    const handleAction = async (id: string, newStatus: string) => {
        try {
            const token = await getToken();
            const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/drafts/${id}`, {
                method: 'PATCH',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${token}`
                },
                body: JSON.stringify({ status: newStatus })
            });
            if (res.ok) {
                setDrafts(prev => prev.filter(d => d.id !== id));
            }
        } catch (err) {
            console.error("Action failed", err);
        }
    };

    return (
        <DashboardShell>
            <SignedOut>
                <SignedOutPanel message="Sign in to manage drafts." forceRedirectUrl="/login" />
            </SignedOut>

            <SignedIn>
                <DashboardSidebar />
                <main className="flex-1 bg-slate-50 min-h-screen p-8">
                    <div className="max-w-5xl mx-auto space-y-6">
                        <div>
                            <h1 className="text-3xl font-black text-slate-900 flex items-center gap-3">
                                Post Drafts <FileText className="w-6 h-6 text-indigo-600" />
                            </h1>
                            <p className="text-slate-500 mt-1">Review and approve content generated by your agents.</p>
                        </div>

                        {isLoading ? (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {Array(4).fill(0).map((_, i) => (
                                    <div key={i} className="h-48 bg-white rounded-3xl animate-pulse border border-slate-100" />
                                ))}
                            </div>
                        ) : drafts.length === 0 ? (
                            <div className="bg-white rounded-3xl p-16 text-center border border-slate-100 shadow-sm">
                                <div className="w-20 h-20 bg-indigo-50 rounded-full flex items-center justify-center mx-auto mb-6">
                                    <FileText className="w-10 h-10 text-indigo-300" />
                                </div>
                                <h3 className="text-xl font-bold text-slate-900">Queue is empty</h3>
                                <p className="text-slate-500 max-w-sm mx-auto mt-2">
                                    When your agents generate content ideas, they will appear here for your approval.
                                </p>
                            </div>
                        ) : (
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {drafts.map((draft) => (
                                    <div key={draft.id} className="bg-white rounded-3xl p-6 border border-slate-100 shadow-sm hover:shadow-md transition-all flex flex-col h-full">
                                        <div className="flex items-center justify-between mb-4">
                                            <div className="flex items-center gap-2">
                                                <div className={`p-1.5 rounded-lg ${draft.platform === 'linkedin' ? 'bg-[#0077b5]/10 text-[#0077b5]' : 'bg-black/10 text-black'}`}>
                                                    {draft.platform === 'linkedin' ? <Linkedin className="w-4 h-4" /> : <Twitter className="w-4 h-4" />}
                                                </div>
                                                <span className="text-[10px] font-black uppercase tracking-widest text-slate-400">
                                                    {draft.platform} Draft
                                                </span>
                                            </div>
                                            <span className="text-[10px] font-bold text-indigo-600 px-2 py-1 bg-indigo-50 rounded-md">
                                                By {draft.agent}
                                            </span>
                                        </div>

                                        <p className="text-slate-700 text-sm leading-relaxed flex-1 mb-6">
                                            {draft.content}
                                        </p>

                                        <div className="flex items-center justify-between pt-6 border-t border-slate-50">
                                            <div className="flex items-center gap-1.5 text-slate-400">
                                                <Clock className="w-3.5 h-3.5" />
                                                <span className="text-[10px] font-bold">Today, 9:00 AM</span>
                                            </div>

                                            <div className="flex items-center gap-2">
                                                <button
                                                    onClick={() => handleAction(draft.id, 'rejected')}
                                                    className="p-2.5 bg-slate-50 text-slate-400 rounded-xl hover:bg-red-50 hover:text-red-500 transition-all"
                                                >
                                                    <X className="w-4 h-4" />
                                                </button>
                                                <button className="p-2.5 bg-slate-50 text-slate-400 rounded-xl hover:bg-slate-100 hover:text-slate-900 transition-all">
                                                    <Edit3 className="w-4 h-4" />
                                                </button>
                                                <button
                                                    onClick={() => handleAction(draft.id, 'approved')}
                                                    className="flex items-center gap-2 px-5 py-2.5 bg-indigo-600 text-white rounded-xl text-xs font-black uppercase tracking-widest hover:bg-indigo-700 shadow-lg shadow-indigo-200 transition-all active:scale-95"
                                                >
                                                    <Check className="w-4 h-4" />
                                                    Approve
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </main>
            </SignedIn>
        </DashboardShell>
    );
}


